// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Tasks': string;
  'TasksHeader': string;
}
declare const cssExports: CssExports;
export = cssExports;
